# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyRawAmazon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NODE_ID', models.CharField(editable=False, max_length=256, null=True)),
                ('High_level_category', models.CharField(editable=False, max_length=256, null=True)),
                ('level_0', models.CharField(editable=False, max_length=256, null=True)),
                ('level_1', models.CharField(editable=False, max_length=256, null=True)),
                ('level_2', models.CharField(blank=True, editable=False, max_length=256, null=True)),
                ('level_3', models.CharField(blank=True, editable=False, max_length=256, null=True)),
                ('level_4', models.CharField(blank=True, editable=False, max_length=256, null=True)),
                ('level_5', models.CharField(blank=True, editable=False, max_length=256, null=True)),
                ('level_6', models.CharField(blank=True, editable=False, max_length=256, null=True)),
                ('level_7', models.CharField(blank=True, editable=False, max_length=256, null=True)),
            ],
        ),
    ]
