# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_taxonomyrawgoogle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyAbridgedAmazon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_0', models.CharField(editable=False, max_length=256, null=True)),
                ('level_1', models.CharField(editable=False, max_length=256, null=True)),
                ('level_2', models.CharField(blank=True, editable=False, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxonomyAbridgedGoogle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_0', models.CharField(editable=False, max_length=256, null=True)),
                ('level_1', models.CharField(editable=False, max_length=256, null=True)),
            ],
        ),
    ]
