# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_taxonomyabridgedamazon_taxonomyabridgedgoogle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTaxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=256, null=True)),
                ('lineage_tags', models.CharField(blank=True, editable=False, max_length=256, null=True, unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='taxonomy.ProductTaxonomy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
