# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0005_auto_20170424_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttaxonomy',
            name='update_model_taxonomy',
            field=models.BooleanField(default=False),
        ),
    ]
