# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0006_producttaxonomy_update_model_taxonomy'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopLevelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=256, null=True)),
                ('slug', models.SlugField(editable=False, max_length=256, null=True)),
                ('image', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
