# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0007_toplevelcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toplevelcategory',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='toplevelcategory',
            name='slug',
            field=models.SlugField(max_length=256, null=True),
        ),
    ]
