# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-18 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0008_auto_20170424_0120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaxonomyAbridgedGoogle',
            new_name='RawTaxonomy',
        ),
        migrations.DeleteModel(
            name='TaxonomyAbridgedAmazon',
        ),
        migrations.DeleteModel(
            name='TaxonomyRawAmazon',
        ),
        migrations.DeleteModel(
            name='TaxonomyRawGoogle',
        ),
    ]
